### ISSUE TITLE
Company website verification

### ISSUE THREAD

**Issue by oskardex** [xdacco/xdac-dapp#1]
Based on users feedback we need to integrate verification of company website in registration and company detail forms and display status on the token sale page. 

**Reasoning**
Anyone can create a company with links to 3rd party project and pretend they are the owner of the company. Investors can invest and if scammers control 51% of the company, they can gain control over collected funds.

**Solution**
The company starting on xDAC platform needs to verify ownership of their company website by uploading a file to their server or by adding &lt;meta&gt; tag to their homepage. 
Example of meta tag:
&lt;HTML&gt;
&lt;HEAD&gt;
&lt;TITLE&gt;Your Title&lt;/TITLE&gt;
&lt;meta name=\"xdac-verification\" content=\"Your_company_account_name\"&gt;
&lt;/HEAD&gt;
&lt;BODY&gt;

Add Company Website field to company registration form and add following states:
- [x] 1) Before the user enters company account name, the download link and verification button are disabled.
- [x] 2) After the user enters company account name, the app will generate accountname.html, which user can download and upload to root folder of his website. 
- [x] 3) The user enters the domain. After entering a valid URL verification button is active.
- [x] 4) The app will verify URL (http://domain/accountname.html) and confirms verification. After successful verification domain is disabled for editing. The field can be reset only when the user refreshes the page.
- [x] 5) If the user tries to submit a form without domain verification error is displayed. (Don't return error on testnet)

- [x] 6) Company website status on the token sale page.

![url-verification](https://user-images.githubusercontent.com/36649800/47588924-87798580-d91c-11e8-9c1b-0c7a26d4979d.jpg)
![image](https://user-images.githubusercontent.com/36649800/47592526-851d2880-d928-11e8-8efb-57e6e35db9fb.png)

**Comment by oskardex** [comment]
- [ ] Issues 4 doesn't seem to work. Try to verify URL http://xbase.exchange/ with username starexplorer - (http://xbase.exchange/starexplorer.html is present).
- [ ] Website verification needs to be integrated into company edit form as well. The same UI can be applied.

**Comment by oskardex** [comment]
Please, just add "?" to Company Website field with a link to help.

**Comment by isaevslava** [comment]
Done
