### ISSUE TITLE
Referral link

### ISSUE THREAD

**Issue by oskardex** [xdacco/xdac-dapp#10]
- [x] Based on user requests we would like to integrate referral program so referrals can bring new companies to the xDAC platform. Referral link should be in format https://xdac.co/r/accountname. Once someone clicks on this link, it will open company registration and saves company to user account who referred this company. 
Later we can add referrals to the user wallet and display all companies this user referred.

**Comment by isaevslava** [comment]
This functionality is ready both from Dmytro's and my side. This user: https://test.xdac.net/registration/testusrxdacc can be replaced with another one.

**Comment by isaevslava** [comment]
Replaced "registration" with "r"
