### ISSUE TITLE
Redo Buy equity by founder

### ISSUE THREAD

**Issue by oskardex** [xdacco/xdac-dapp#11]
We have a few updates in buy equity form to make the process of company registration more straightforward. Also, founders have a hard time to understand rules when it comes to who controls the company and this update should help it.

- [x] Founders can slide between different accounts to select the one they want to use. If the founder has only one account, we can hide arrows.

- [x] Amount of tokens should be editable. Founders can either slide to the desired number of tokens they want to buy or enter the exact amount.

 - [x] Under slider we will display the following texts:
If founder selects less than 50%: **You need partners with *"remaining_amount_to_50p_of_the_volume_+_1"* "SYMBOL" to control the company.**
If founder selects anything between 50% and 100%: **You control the company.**
If founder selects 100%: **The company is yours.**

- [x] If the remaining balance is less than 0, we should disable BUY button.

![image](https://user-images.githubusercontent.com/36649800/59903024-c16c3000-93b4-11e9-91ca-15e1d9a23035.png)
![image](https://user-images.githubusercontent.com/36649800/59903698-810db180-93b6-11e9-945b-69a3ebe39677.png)

**Comment by isaevslava** [comment]
1. What if a user has XDACs on his balance and they are enough to buy tokens? Metamask button isn't needed. It will mislead the user.
2. If the user has XDACs, but they are not enough for a purchase. We need to buy missing tokens via Metamask or to buy full of them via MetaMask?
3. If there are no XDACs, we will load the wallet and after it is credited automatically create a company. The company is created with XDAC.
